### ISSUE TITLE
Installation failure VS2019 preview

### ISSUE THREAD

**Issue by mkurdej** [brianschmitt/relativenumber#18]
VS2019 preview is apparently not supported yet.
I get this error in the log:
```
2018-12-07 15:44:15 - The extension with ID 'RelativeNumber.Microsoft.b75ccaea-70c1-475c-9cb7-ddb84ea9d43c' is not installed to Microsoft Visual Studio Enterprise 2019.
2018-12-07 15:44:18 - Extension cannot be installed to the following products due to missing prerequisites:
2018-12-07 15:44:18 - 	Microsoft Visual Studio Enterprise 2019
2018-12-07 15:44:18 - 		-------------------------------------------------------
2018-12-07 15:44:18 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
2018-12-07 15:44:18 - 		Name         : Visual Studio core editor
2018-12-07 15:44:18 - 		Version      : [15.0,16.0)
2018-12-07 15:44:18 - 		Error        : The prerequisite version specified does not match the version installed
2018-12-07 15:44:18 - 
2018-12-07 15:44:18 - System.InvalidOperationException: No modifications could be applied.
   at VSIXInstaller.MultipleChangePage..ctor(ExtensionData data)
   at VSIXInstaller.LoadingPage.<>c__DisplayClass15_1.<OnLoaded>b__2()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

I manually changed the required version of `Microsoft.VisualStudio.Component.CoreEditor` to `[15.0, 16.0]` but that fails too with:
```
2018-12-07 15:49:55 - Beginning to install extension to Visual Studio Enterprise 2019 Preview...
2018-12-07 15:49:57 - Install Error : Microsoft.VisualStudio.ExtensionManager.MissingReferencesException: This extension cannot be installed because the following references are missing:
-Microsoft.VisualStudio.Component.CoreEditor (Microsoft.VisualStudio.Component.CoreEditor)
   at Microsoft.VisualStudio.ExtensionManager.EngineUtilities.EnsureNoMissingReferences(IEnumerable`1 missingRefs)
   at Microsoft.VisualStudio.ExtensionManager.PackageInstaller.PrepareEngineInstall(IDependencyGraph dGraph, IDependencyComparisonSeed seed, Component vsCompPkg, Boolean isProductComponent, Int32& totalInstallationSteps)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)
```

**Comment by brianschmitt** [comment]
Just pushed version 1.6 to the Marketplace, which adds support for 2019.

**Comment by mkurdej** [comment]
Great! It works perfectly!
