### ISSUE TITLE
Installation Failure VS2013, VS2015

### ISSUE THREAD

**Issue by ashutoshraina** [brianschmitt/relativenumber#7]
Installation Log

```
2/8/2015 1:30:59 AM - Microsoft VSIX Installer
2/8/2015 1:30:59 AM - -------------------------------------------
2/8/2015 1:30:59 AM - Initializing Install...
2/8/2015 1:30:59 AM - Extension Details...
2/8/2015 1:30:59 AM - 	Identifier      : RelativeNumber.Microsoft.b75ccaea-70c1-475c-9cb7-ddb84ea9d43c
2/8/2015 1:30:59 AM - 	Name            : Relative Number
2/8/2015 1:30:59 AM - 	Author          : Brian Schmitt
2/8/2015 1:30:59 AM - 	Version         : 1.4.0
2/8/2015 1:30:59 AM - 	Description     : Displays the line number relative to the line with the cursor on it. It allows you to make quick vertical movements. 
2/8/2015 1:30:59 AM - 	Locale          : en-US
2/8/2015 1:30:59 AM - 	MoreInfoURL     : https://github.com/brianschmitt/relativenumber
2/8/2015 1:30:59 AM - 	InstalledByMSI  : False
2/8/2015 1:30:59 AM - 	SupportedFrameworkVersionRange : [4.5]
2/8/2015 1:30:59 AM - 
2/8/2015 1:30:59 AM - 	Supported Products : 
2/8/2015 1:30:59 AM - 		Microsoft.VisualStudio.Pro
2/8/2015 1:30:59 AM - 			Version : [11.0,)
2/8/2015 1:30:59 AM - 		Microsoft.VisualStudio.Premium
2/8/2015 1:30:59 AM - 			Version : [11.0,)
2/8/2015 1:30:59 AM - 		Microsoft.VisualStudio.Ultimate
2/8/2015 1:30:59 AM - 			Version : [11.0,)
2/8/2015 1:30:59 AM - 
2/8/2015 1:30:59 AM - 	References      : 
2/8/2015 1:30:59 AM - 
2/8/2015 1:30:59 AM - Searching for applicable products...
2/8/2015 1:30:59 AM - Found installed product - Microsoft Visual Studio Professional 2013
2/8/2015 1:31:00 AM - The extension with ID 'RelativeNumber.Microsoft.b75ccaea-70c1-475c-9cb7-ddb84ea9d43c' is not installed to Microsoft Visual Studio Professional 2013.
2/8/2015 1:31:00 AM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
2/8/2015 1:31:00 AM - Found installed product - Microsoft Visual Studio Ultimate 2015 CTP
2/8/2015 1:31:01 AM - The extension with ID 'RelativeNumber.Microsoft.b75ccaea-70c1-475c-9cb7-ddb84ea9d43c' is not installed to Microsoft Visual Studio Ultimate 2015 CTP.
2/8/2015 1:31:01 AM - Found installed product - Microsoft Visual Studio Premium 2015 CTP
2/8/2015 1:31:01 AM - Found installed product - Microsoft Visual Studio Professional 2015 CTP
2/8/2015 1:31:01 AM - Found installed product - Microsoft Visual Studio Community 2015 CTP
2/8/2015 1:31:01 AM - Found installed product - Microsoft Visual Studio 2015 CTP Shell (Integrated)
2/8/2015 1:31:01 AM - Found installed product - Global Location
2/8/2015 1:31:04 AM - The following target products have been selected...
2/8/2015 1:31:04 AM - 	Microsoft Visual Studio Professional 2013
2/8/2015 1:31:04 AM - 	Microsoft Visual Studio Ultimate 2015 CTP
2/8/2015 1:31:04 AM - 
2/8/2015 1:31:04 AM - Beginning to install extension to Microsoft Visual Studio Professional 2013...
2/8/2015 1:31:04 AM - Install Error : Microsoft.VisualStudio.ExtensionManager.MissingTargetFrameworkException: The extension 'Relative Number' requires a version of the .NET Framework that is not installed.
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.CheckForValidDotNetFramework(IExtension extension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.CheckForInstallBlockers(InstallableExtensionImpl extension, IInstalledExtensionList modifiedInstalledExtensionsList, Boolean isNestedExtension, Boolean& olderVersionInstalled)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallInternal(InstallableExtensionImpl extension, Boolean perMachine, Boolean isNestedExtension, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, UInt64 totalBytesToWrite, UInt64& totalBytesWritten)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.BeginInstall(IInstallableExtension installableExtension, Boolean perMachine, AsyncOperation asyncOp)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallWorker(IInstallableExtension extension, Boolean perMachine, AsyncOperation asyncOp)
2/8/2015 1:31:05 AM - Beginning to install extension to Microsoft Visual Studio Ultimate 2015 CTP...
2/8/2015 1:31:05 AM - Install Error : Microsoft.VisualStudio.ExtensionManager.MissingTargetFrameworkException: The extension 'Relative Number' requires a version of the .NET Framework that is not installed.
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.CheckForValidDotNetFramework(IExtension extension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.CheckForInstallBlockers(InstallableExtensionImpl extension, IInstalledExtensionList modifiedInstalledExtensionsList, Boolean isNestedExtension, Boolean& olderVersionInstalled)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallInternal(InstallableExtensionImpl extension, Boolean perMachine, Boolean isNestedExtension, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, UInt64 totalBytesToWrite, UInt64& totalBytesWritten)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.BeginInstall(IInstallableExtension installableExtension, Boolean perMachine, AsyncOperation asyncOp)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallWorker(IInstallableExtension extension, Boolean perMachine, AsyncOperation asyncOp)

```

I have all the framework versions with me. So, what am I missing ? Can we relax the framework version requirements ?

**Comment by brianschmitt** [comment]
Hmm. There isn't a specific framework that we are targeting, just what we compiled against. Are you able to successfully get the source and build it, or is that failing too?  In the next day or two, I will fire up a VM with only 2013 and 2105 installed to see if I can get a version working for you.

**Comment by ashutoshraina** [comment]
This probably requires the visual studio sdk, which I don't have. The build fails with the following error 

```
error MSB4019:
The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v12.0\VSSDK\Microsoft.VsSDK.target
s" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on di
sk.
Done Building Project "C:\Users\ashutosh\Documents\Github\relativenumber\RelativeNumber\RelativeNumber.csproj"
 (default targets) -- FAILED.

Done Building Project "C:\Users\ashutosh\Documents\Github\relativenumber\RelativeNumber.sln" (default targets)
 -- FAILED.


```

I tried building it with both MSBuild 14 & 12.

**Comment by brianschmitt** [comment]
Can you try the 1.4.1 Build: https://github.com/brianschmitt/relativenumber/releases/tag/1.4.1
There was a hard dependency in the manifest file, which I removed.

**Comment by ashutoshraina** [comment]
Tried it out, installs on both versions of VS. Works on VS2013, doesn't work on VS2015.

**Comment by brianschmitt** [comment]
I cannot reproduce the issue, I tried it on Win 2012, Win 10, Win 8.1. All with just VS2015 installed and with 2013 installed. Can you provide what OS you are running?

Can you explain what isn't working in 2015? Do you see normal line numbers? Just for kicks, can you turn line numbers off/on in the Tools>Options>Text Editor>All Languages>General section?

I did encounter an issue where the plugin was disabled in 2015, but enabling it, allowed it to work as expected. I believe this issue was caused by me installing the plugin as VS was starting up.

Thanks!!

**Comment by ashutoshraina** [comment]
Works...probably the Azure vm didn't like it..but worked on my Win 8 machine...awesome and thanks for this :+1:
